/*
This file was generated by Nickk's TextDraw editor script
Nickk888 is the author of the NTD script
*/

#include <a_samp>

new PlayerText:BAR1[MAX_PLAYERS];
new PlayerText:BAR2[MAX_PLAYERS];
new PlayerText:BAR3[MAX_PLAYERS];
new PlayerText:BAR4[MAX_PLAYERS];
new PlayerText:BARLOGO[MAX_PLAYERS];
new PlayerText:BARPERSEN[MAX_PLAYERS];
new PlayerText:BAR5[MAX_PLAYERS];
new PlayerText:BAR6[MAX_PLAYERS];
new PlayerText:BAR7[MAX_PLAYERS];
new PlayerText:PERSENBAR[MAX_PLAYERS];
new PlayerText:BARLOGODINER[MAX_PLAYERS];
new PlayerText:BAR8[MAX_PLAYERS];

public OnFilterScriptInit()
{
	return 1;
}

public OnFilterScriptExit()
{
	return 1;
}

public OnPlayerConnect(playerid)
{
	BAR1[playerid] = CreatePlayerTextDraw(playerid, 553.000000, 103.000000, "ld_dual:white");
	PlayerTextDrawFont(playerid, BAR1[playerid], 4);
	PlayerTextDrawLetterSize(playerid, BAR1[playerid], 0.600000, 2.000000);
	PlayerTextDrawTextSize(playerid, BAR1[playerid], 56.500000, 23.500000);
	PlayerTextDrawSetOutline(playerid, BAR1[playerid], 1);
	PlayerTextDrawSetShadow(playerid, BAR1[playerid], 0);
	PlayerTextDrawAlignment(playerid, BAR1[playerid], 1);
	PlayerTextDrawColor(playerid, BAR1[playerid], 255);
	PlayerTextDrawBackgroundColor(playerid, BAR1[playerid], 255);
	PlayerTextDrawBoxColor(playerid, BAR1[playerid], 50);
	PlayerTextDrawUseBox(playerid, BAR1[playerid], 1);
	PlayerTextDrawSetProportional(playerid, BAR1[playerid], 1);
	PlayerTextDrawSetSelectable(playerid, BAR1[playerid], 0);

	BAR2[playerid] = CreatePlayerTextDraw(playerid, 554.000000, 105.000000, "ld_dual:white");
	PlayerTextDrawFont(playerid, BAR2[playerid], 4);
	PlayerTextDrawLetterSize(playerid, BAR2[playerid], 0.600000, 2.000000);
	PlayerTextDrawTextSize(playerid, BAR2[playerid], 54.500000, 20.500000);
	PlayerTextDrawSetOutline(playerid, BAR2[playerid], 1);
	PlayerTextDrawSetShadow(playerid, BAR2[playerid], 0);
	PlayerTextDrawAlignment(playerid, BAR2[playerid], 1);
	PlayerTextDrawColor(playerid, BAR2[playerid], 1296911871);
	PlayerTextDrawBackgroundColor(playerid, BAR2[playerid], 255);
	PlayerTextDrawBoxColor(playerid, BAR2[playerid], 50);
	PlayerTextDrawUseBox(playerid, BAR2[playerid], 1);
	PlayerTextDrawSetProportional(playerid, BAR2[playerid], 1);
	PlayerTextDrawSetSelectable(playerid, BAR2[playerid], 0);

	BAR3[playerid] = CreatePlayerTextDraw(playerid, 575.000000, 108.000000, "ld_dual:white");
	PlayerTextDrawFont(playerid, BAR3[playerid], 4);
	PlayerTextDrawLetterSize(playerid, BAR3[playerid], 0.600000, 2.000000);
	PlayerTextDrawTextSize(playerid, BAR3[playerid], 30.000000, 13.000000);
	PlayerTextDrawSetOutline(playerid, BAR3[playerid], 1);
	PlayerTextDrawSetShadow(playerid, BAR3[playerid], 0);
	PlayerTextDrawAlignment(playerid, BAR3[playerid], 1);
	PlayerTextDrawColor(playerid, BAR3[playerid], -16776961);
	PlayerTextDrawBackgroundColor(playerid, BAR3[playerid], 255);
	PlayerTextDrawBoxColor(playerid, BAR3[playerid], 50);
	PlayerTextDrawUseBox(playerid, BAR3[playerid], 1);
	PlayerTextDrawSetProportional(playerid, BAR3[playerid], 1);
	PlayerTextDrawSetSelectable(playerid, BAR3[playerid], 0);

	BAR4[playerid] = CreatePlayerTextDraw(playerid, 569.000000, 105.000000, "ld_dual:white");
	PlayerTextDrawFont(playerid, BAR4[playerid], 4);
	PlayerTextDrawLetterSize(playerid, BAR4[playerid], 0.600000, 2.000000);
	PlayerTextDrawTextSize(playerid, BAR4[playerid], 1.500000, 20.500000);
	PlayerTextDrawSetOutline(playerid, BAR4[playerid], 1);
	PlayerTextDrawSetShadow(playerid, BAR4[playerid], 0);
	PlayerTextDrawAlignment(playerid, BAR4[playerid], 1);
	PlayerTextDrawColor(playerid, BAR4[playerid], 255);
	PlayerTextDrawBackgroundColor(playerid, BAR4[playerid], 255);
	PlayerTextDrawBoxColor(playerid, BAR4[playerid], 50);
	PlayerTextDrawUseBox(playerid, BAR4[playerid], 1);
	PlayerTextDrawSetProportional(playerid, BAR4[playerid], 1);
	PlayerTextDrawSetSelectable(playerid, BAR4[playerid], 0);

	BARLOGO[playerid] = CreatePlayerTextDraw(playerid, 554.000000, 108.000000, "HUD:radar_datefood");
	PlayerTextDrawFont(playerid, BARLOGO[playerid], 4);
	PlayerTextDrawLetterSize(playerid, BARLOGO[playerid], 0.600000, 2.000000);
	PlayerTextDrawTextSize(playerid, BARLOGO[playerid], 12.500000, 14.000000);
	PlayerTextDrawSetOutline(playerid, BARLOGO[playerid], 1);
	PlayerTextDrawSetShadow(playerid, BARLOGO[playerid], 0);
	PlayerTextDrawAlignment(playerid, BARLOGO[playerid], 1);
	PlayerTextDrawColor(playerid, BARLOGO[playerid], -1);
	PlayerTextDrawBackgroundColor(playerid, BARLOGO[playerid], 255);
	PlayerTextDrawBoxColor(playerid, BARLOGO[playerid], 50);
	PlayerTextDrawUseBox(playerid, BARLOGO[playerid], 1);
	PlayerTextDrawSetProportional(playerid, BARLOGO[playerid], 1);
	PlayerTextDrawSetSelectable(playerid, BARLOGO[playerid], 0);

	BARPERSEN[playerid] = CreatePlayerTextDraw(playerid, 581.000000, 109.000000, "100");
	PlayerTextDrawFont(playerid, BARPERSEN[playerid], 3);
	PlayerTextDrawLetterSize(playerid, BARPERSEN[playerid], 0.229167, 0.950000);
	PlayerTextDrawTextSize(playerid, BARPERSEN[playerid], 400.000000, 17.000000);
	PlayerTextDrawSetOutline(playerid, BARPERSEN[playerid], 1);
	PlayerTextDrawSetShadow(playerid, BARPERSEN[playerid], 0);
	PlayerTextDrawAlignment(playerid, BARPERSEN[playerid], 1);
	PlayerTextDrawColor(playerid, BARPERSEN[playerid], -1);
	PlayerTextDrawBackgroundColor(playerid, BARPERSEN[playerid], 255);
	PlayerTextDrawBoxColor(playerid, BARPERSEN[playerid], 50);
	PlayerTextDrawUseBox(playerid, BARPERSEN[playerid], 0);
	PlayerTextDrawSetProportional(playerid, BARPERSEN[playerid], 1);
	PlayerTextDrawSetSelectable(playerid, BARPERSEN[playerid], 0);

	BAR5[playerid] = CreatePlayerTextDraw(playerid, 553.000000, 128.000000, "ld_dual:white");
	PlayerTextDrawFont(playerid, BAR5[playerid], 4);
	PlayerTextDrawLetterSize(playerid, BAR5[playerid], 0.600000, 2.000000);
	PlayerTextDrawTextSize(playerid, BAR5[playerid], 56.500000, 23.500000);
	PlayerTextDrawSetOutline(playerid, BAR5[playerid], 1);
	PlayerTextDrawSetShadow(playerid, BAR5[playerid], 0);
	PlayerTextDrawAlignment(playerid, BAR5[playerid], 1);
	PlayerTextDrawColor(playerid, BAR5[playerid], 255);
	PlayerTextDrawBackgroundColor(playerid, BAR5[playerid], 255);
	PlayerTextDrawBoxColor(playerid, BAR5[playerid], 50);
	PlayerTextDrawUseBox(playerid, BAR5[playerid], 1);
	PlayerTextDrawSetProportional(playerid, BAR5[playerid], 1);
	PlayerTextDrawSetSelectable(playerid, BAR5[playerid], 0);

	BAR6[playerid] = CreatePlayerTextDraw(playerid, 554.000000, 130.000000, "ld_dual:white");
	PlayerTextDrawFont(playerid, BAR6[playerid], 4);
	PlayerTextDrawLetterSize(playerid, BAR6[playerid], 0.600000, 2.000000);
	PlayerTextDrawTextSize(playerid, BAR6[playerid], 54.500000, 20.500000);
	PlayerTextDrawSetOutline(playerid, BAR6[playerid], 1);
	PlayerTextDrawSetShadow(playerid, BAR6[playerid], 0);
	PlayerTextDrawAlignment(playerid, BAR6[playerid], 1);
	PlayerTextDrawColor(playerid, BAR6[playerid], 1296911871);
	PlayerTextDrawBackgroundColor(playerid, BAR6[playerid], 255);
	PlayerTextDrawBoxColor(playerid, BAR6[playerid], 50);
	PlayerTextDrawUseBox(playerid, BAR6[playerid], 1);
	PlayerTextDrawSetProportional(playerid, BAR6[playerid], 1);
	PlayerTextDrawSetSelectable(playerid, BAR6[playerid], 0);

	BAR7[playerid] = CreatePlayerTextDraw(playerid, 575.000000, 133.000000, "ld_dual:white");
	PlayerTextDrawFont(playerid, BAR7[playerid], 4);
	PlayerTextDrawLetterSize(playerid, BAR7[playerid], 0.600000, 2.000000);
	PlayerTextDrawTextSize(playerid, BAR7[playerid], 30.000000, 13.000000);
	PlayerTextDrawSetOutline(playerid, BAR7[playerid], 1);
	PlayerTextDrawSetShadow(playerid, BAR7[playerid], 0);
	PlayerTextDrawAlignment(playerid, BAR7[playerid], 1);
	PlayerTextDrawColor(playerid, BAR7[playerid], 9145343);
	PlayerTextDrawBackgroundColor(playerid, BAR7[playerid], 255);
	PlayerTextDrawBoxColor(playerid, BAR7[playerid], 50);
	PlayerTextDrawUseBox(playerid, BAR7[playerid], 1);
	PlayerTextDrawSetProportional(playerid, BAR7[playerid], 1);
	PlayerTextDrawSetSelectable(playerid, BAR7[playerid], 0);

	PERSENBAR[playerid] = CreatePlayerTextDraw(playerid, 582.000000, 134.000000, "100");
	PlayerTextDrawFont(playerid, PERSENBAR[playerid], 3);
	PlayerTextDrawLetterSize(playerid, PERSENBAR[playerid], 0.229167, 0.950000);
	PlayerTextDrawTextSize(playerid, PERSENBAR[playerid], 400.000000, 17.000000);
	PlayerTextDrawSetOutline(playerid, PERSENBAR[playerid], 1);
	PlayerTextDrawSetShadow(playerid, PERSENBAR[playerid], 0);
	PlayerTextDrawAlignment(playerid, PERSENBAR[playerid], 1);
	PlayerTextDrawColor(playerid, PERSENBAR[playerid], -1);
	PlayerTextDrawBackgroundColor(playerid, PERSENBAR[playerid], 255);
	PlayerTextDrawBoxColor(playerid, PERSENBAR[playerid], 50);
	PlayerTextDrawUseBox(playerid, PERSENBAR[playerid], 0);
	PlayerTextDrawSetProportional(playerid, PERSENBAR[playerid], 1);
	PlayerTextDrawSetSelectable(playerid, PERSENBAR[playerid], 0);

	BARLOGODINER[playerid] = CreatePlayerTextDraw(playerid, 555.000000, 132.000000, "HUD:radar_diner");
	PlayerTextDrawFont(playerid, BARLOGODINER[playerid], 4);
	PlayerTextDrawLetterSize(playerid, BARLOGODINER[playerid], 0.600000, 2.000000);
	PlayerTextDrawTextSize(playerid, BARLOGODINER[playerid], 12.500000, 14.000000);
	PlayerTextDrawSetOutline(playerid, BARLOGODINER[playerid], 1);
	PlayerTextDrawSetShadow(playerid, BARLOGODINER[playerid], 0);
	PlayerTextDrawAlignment(playerid, BARLOGODINER[playerid], 1);
	PlayerTextDrawColor(playerid, BARLOGODINER[playerid], -1);
	PlayerTextDrawBackgroundColor(playerid, BARLOGODINER[playerid], 255);
	PlayerTextDrawBoxColor(playerid, BARLOGODINER[playerid], 50);
	PlayerTextDrawUseBox(playerid, BARLOGODINER[playerid], 1);
	PlayerTextDrawSetProportional(playerid, BARLOGODINER[playerid], 1);
	PlayerTextDrawSetSelectable(playerid, BARLOGODINER[playerid], 0);

	BAR8[playerid] = CreatePlayerTextDraw(playerid, 569.000000, 130.000000, "ld_dual:white");
	PlayerTextDrawFont(playerid, BAR8[playerid], 4);
	PlayerTextDrawLetterSize(playerid, BAR8[playerid], 0.600000, 2.000000);
	PlayerTextDrawTextSize(playerid, BAR8[playerid], 1.500000, 20.500000);
	PlayerTextDrawSetOutline(playerid, BAR8[playerid], 1);
	PlayerTextDrawSetShadow(playerid, BAR8[playerid], 0);
	PlayerTextDrawAlignment(playerid, BAR8[playerid], 1);
	PlayerTextDrawColor(playerid, BAR8[playerid], 255);
	PlayerTextDrawBackgroundColor(playerid, BAR8[playerid], 255);
	PlayerTextDrawBoxColor(playerid, BAR8[playerid], 50);
	PlayerTextDrawUseBox(playerid, BAR8[playerid], 1);
	PlayerTextDrawSetProportional(playerid, BAR8[playerid], 1);
	PlayerTextDrawSetSelectable(playerid, BAR8[playerid], 0);

	return 1;
}

public OnPlayerDisconnect(playerid, reason)
{
	PlayerTextDrawDestroy(playerid, BAR1[playerid]);
	PlayerTextDrawDestroy(playerid, BAR2[playerid]);
	PlayerTextDrawDestroy(playerid, BAR3[playerid]);
	PlayerTextDrawDestroy(playerid, BAR4[playerid]);
	PlayerTextDrawDestroy(playerid, BARLOGO[playerid]);
	PlayerTextDrawDestroy(playerid, BARPERSEN[playerid]);
	PlayerTextDrawDestroy(playerid, BAR5[playerid]);
	PlayerTextDrawDestroy(playerid, BAR6[playerid]);
	PlayerTextDrawDestroy(playerid, BAR7[playerid]);
	PlayerTextDrawDestroy(playerid, PERSENBAR[playerid]);
	PlayerTextDrawDestroy(playerid, BARLOGODINER[playerid]);
	PlayerTextDrawDestroy(playerid, BAR8[playerid]);
	return 1;
}

public OnPlayerCommandText(playerid, cmdtext[])
{
	if(!strcmp(cmdtext, "/tdtest", true))
	{
		PlayerTextDrawShow(playerid, BAR1[playerid]);
		PlayerTextDrawShow(playerid, BAR2[playerid]);
		PlayerTextDrawShow(playerid, BAR3[playerid]);
		PlayerTextDrawShow(playerid, BAR4[playerid]);
		PlayerTextDrawShow(playerid, BARLOGO[playerid]);
		PlayerTextDrawShow(playerid, BARPERSEN[playerid]);
		PlayerTextDrawShow(playerid, BAR5[playerid]);
		PlayerTextDrawShow(playerid, BAR6[playerid]);
		PlayerTextDrawShow(playerid, BAR7[playerid]);
		PlayerTextDrawShow(playerid, PERSENBAR[playerid]);
		PlayerTextDrawShow(playerid, BARLOGODINER[playerid]);
		PlayerTextDrawShow(playerid, BAR8[playerid]);
		return 1;
	}
	return 0;
}
